import Head from 'next/head'
import Image from 'next/image'
import styles from '@/styles/Home.module.scss'

//_ COMPONENTS
import Project from '../../components/project';
import SourceList from '../../components/sourceList';


export default function Home() {

    return (
        <>
            <Head>
                <title>Coming Soon...</title>
                <meta name="description" content="Generated by create next app" />
                <meta name="viewport" content="width=device-width, initial-scale=1" />
                <link rel="icon" href="/favicon.ico" />
            </Head>
            <main id={styles.main}>
                <section id={styles.section}>
                    <h1>Coming soon...</h1>
                    <Image id={styles.image} width={48} height={48} src="/favicon-32x32.png" alt="therefore Logo" />
                    <p>
                        The portfolio site is on hold as I am currently occupied with some other projects, namely:
                    </p>
                    <div id={styles.project_section}>
                        <Project 
                            project_name="integrator" 
                            project_links={{github: "https://github.com/theologicalphysicist/integrator"}} 
                        />
                        <Project 
                            project_name="mh_tracker" 
                            project_links={{
                                github: "https://github.com/theologicalphysicist/mh_tracker",
                                site: "http://mhtrackerunstable.gatsbyjs.io"    
                            }} 
                        />

                    </div>
                    <h3>
                        Check them out!
                    </h3>
                </section>
                <aside id={styles.aside}>
                    <p>
                        This site was built with:
                    </p>
                    <SourceList />
                </aside>
            </main>
        </>
    );
};
